[package]
name = "g213_colours"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9.2"
hex = "0.4.3"
lazy_static = "1.4.0"

[dev-dependencies]

[lib]
doctest = false

[[bin]]
name = "g213-cols"
test = false
bench = false
